<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.OrchardCore.Module.Sdk/Sdk/Import.props" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.props" Sdk="Lombiq.MSBuild.OrchardCore.Module.Sdk" Version="1.0.1-alpha.27.osoe-925" />

  <PropertyGroup>
    <Title>Lombiq Hosting - Build Version Display for Orchard Core</Title>
    <CopyrightYear>2023</CopyrightYear>
    <DescriptionBody>Orchard Core module to display the build version (i.e. .NET assembly version or other) on the admin of the Default tenant.</DescriptionBody>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Hosting;</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Hosting-Build-Version-Display</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <!-- If this is not explicitly specified then OrchardCore.Module.Targets will take over the build folder and it
    won't be included. -->
    <None Include="build\Lombiq.Hosting.BuildVersionDisplay.targets" Pack="true" PackagePath="build\Lombiq.Hosting.BuildVersionDisplay.targets" />
  </ItemGroup>

  <!-- The targets file will be automatically imported when using the project from NuGet but needs an explicit import
  when used from source. -->
  <Import Project="build/Lombiq.Hosting.BuildVersionDisplay.targets" Condition="'$(NuGetBuild)' != 'true'" />

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.OrchardCore.Module.Sdk/Sdk/Import.targets" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.targets" Sdk="Lombiq.MSBuild.OrchardCore.Module.Sdk" Version="1.0.1-alpha.27.osoe-925" />
</Project>
