name: Dump GitHub context

on:
  pull_request:

jobs:
  dump-github-context:
    runs-on: ubuntu-latest
    steps:
    - env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      shell: pwsh
      run: Write-Output $Env:GITHUB_CONTEXT